import Img1 from "../assets/images/eduPI.png";
import Img2 from "../assets/images/artify.png";
import Img3 from "../assets/images/newCampus.png";
import Img4 from "../assets/images/slotify.png";
import Img5 from "../assets/images/caresync.png";
import Img6 from "../assets/images/TubeGate.png";
import Img7 from "../assets/images/notice.png";
import Img8 from "../assets/images/thought.png";
import Img9 from "../assets/images/leetq.png"; // Make sure you add this image
import Img10 from "../assets/images/npm.png"; // Make sure you add this image

export const project = [
  {
    id: 1,
    title: "TubeGate",
    url: "",
    img: Img6,
    desc: "Built an automated YouTube publishing platform with secure OAuth integration...",
    live: "https://tubegate.vercel.app/",
    code: "https://github.com/samar-abbas-786/TubeGate",
    techStack: [
      "Next.js",
      "OAuth 2.0",
      "Prisma ORM",
      "PostgreSQL",
      "Cloudinary",
      "YouTube Data API",
    ],
  },
  {
    id: 2,
    title: "LeetQ – AI Browser Assistant for LeetCode",
    url: "",
    img: Img9,
    desc: "LeetQ is a powerful browser extension that enhances your LeetCode problem-solving...",
    live: "https://drive.google.com/file/d/1kaWuSrmLNgYbP5hKRmpg3r1QwB1F_L56/view?usp=sharing",
    code: "https://github.com/samar-abbas-786/leetcode-browser-extension",
    techStack: [
      "JavaScript",
      "Claude AI API",
      "React (Vite)",
      "Tailwind CSS",
      "Manifest V3",
    ],
  },
  {
    id: 3,
    title: "Samar-Kit : MERN Boilerplate CLI & NPM Package",
    url: "",
    img: Img10,
    desc: "samar-kit is an npm package and CLI tool that instantly scaffolds a production-ready MERN stack app...",
    live: "https://www.npmjs.com/package/samar-kit",
    techStack: [
      "Node.js",
      "Express",
      "MongoDB",
      "React (Vite)",
      "Tailwind CSS",
      "npx",
      "JavaScript",
      "fs-extra",
    ],
  },
  {
    id: 4,
    title: "EduPI",
    url: "",
    img: Img1,
    desc: "Designed and developed a comprehensive school management platform...",
    live: "https://edupi-samar786.vercel.app",
    code: "https://github.com/samar-abbas-786/Minor_Project",
    techStack: ["MongoDB", "Express", "React", "Node.js", "Tailwind CSS"],
  },
  {
    id: 5,
    title: "Artify",
    url: "https://artify-samar.vercel.app/",
    img: Img2,
    desc: "Developed Artify, an online painting marketplace...",
    live: "https://artify-samar.vercel.app/",
    code: "https://github.com/samar-abbas-786/Artify",
    techStack: ["React", "MongoDB", "Express", "Node.js", "Tailwind CSS"],
  },
  {
    id: 6,
    title: "Campus Bazaar",
    url: "https://campus-bazaar.onrender.com/",
    img: Img3,
    desc: "Introducing Campus Bazaar: Simplify college life...",
    live: "https://campus-bazaar-z22g.onrender.com",
    code: "https://github.com/samar-abbas-786/Campus-Bazaar",
    techStack: ["Node.js", "Express", "MongoDB Cluster", "EJS", "CSS"],
  },
  {
    id: 7,
    title: "CareSync",
    url: "https://caresync2-3.onrender.com",
    img: Img5,
    desc: "CareSync, a Healthcare Website, born from a hackathon...",
    live: "https://caresync2-3.onrender.com",
    code: "https://github.com/samar-abbas-786/CareSync2",
    techStack: [
      "Node.js",
      "Express",
      "MongoDB",
      "EJS",
      "CSS",
      "Geolocation API",
      "Kaggle",
    ],
  },
  {
    id: 8,
    title: "Slotify",
    url: "https://gym-website-virid.vercel.app",
    img: Img4,
    desc: "Developed Slotify, an event scheduling platform...",
    code: "https://github.com/samar-abbas-786/Event-Scheduler",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
  },
  {
    id: 9,
    title: "Online Notice Board",
    url: "https://notice-board-vx95.onrender.com",
    img: Img7,
    desc: "Built a digital Notice Board system...",
    code: "https://github.com/samar-abbas-786/Notice-Board",
    techStack: [
      "Next.js",
      "Node.js",
      "Express",
      "Neon Postgres",
      "Tailwind CSS",
    ],
  },
  {
    id: 10,
    title: "Thoughtify",
    url: "https://notice-board-vx95.onrender.com",
    img: Img8,
    desc: "Thoughtify is a digital platform for sharing and exploring thoughts...",
    code: "https://github.com/samar-abbas-786/Thoughtify",
    techStack: ["Next", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
  },
];
